// <auto-generated />
namespace PhantomNet.Entities.Mvc
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.Entities.Mvc.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Manager does not implement IEntityManager&lt;TEntity&gt;.
        /// </summary>
        internal static string ManagerNotIEntityManager
        {
            get { return GetString("ManagerNotIEntityManager"); }
        }

        /// <summary>
        /// Manager does not implement IEntityManager&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatManagerNotIEntityManager()
        {
            return GetString("ManagerNotIEntityManager");
        }

        /// <summary>
        /// Manager does not implement IGroupedEntityManager&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string ManagerNotIGroupedEntityManager
        {
            get { return GetString("ManagerNotIGroupedEntityManager"); }
        }

        /// <summary>
        /// Manager does not implement IGroupedEntityManager&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string FormatManagerNotIGroupedEntityManager()
        {
            return GetString("ManagerNotIGroupedEntityManager");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
