// <auto-generated />
namespace PhantomNet.Entities
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("PhantomNet.Entities.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Optimistic concurrency failure, object has been modified.
        /// </summary>
        internal static string ConcurrencyFailure
        {
            get { return GetString("ConcurrencyFailure"); }
        }

        /// <summary>
        /// Optimistic concurrency failure, object has been modified.
        /// </summary>
        internal static string FormatConcurrencyFailure()
        {
            return GetString("ConcurrencyFailure");
        }

        /// <summary>
        /// An unknown failure has occured.
        /// </summary>
        internal static string DefaultError
        {
            get { return GetString("DefaultError"); }
        }

        /// <summary>
        /// An unknown failure has occured.
        /// </summary>
        internal static string FormatDefaultError()
        {
            return GetString("DefaultError");
        }

        /// <summary>
        /// Generic class {0} must also be used as class parameter.
        /// </summary>
        internal static string GenericClassNotMatched
        {
            get { return GetString("GenericClassNotMatched"); }
        }

        /// <summary>
        /// Generic class {0} must also be used as class parameter.
        /// </summary>
        internal static string FormatGenericClassNotMatched(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("GenericClassNotMatched"), p0);
        }

        /// <summary>
        /// Store does not implement ICodeBasedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotICodeBasedEntityStore
        {
            get { return GetString("StoreNotICodeBasedEntityStore"); }
        }

        /// <summary>
        /// Store does not implement ICodeBasedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotICodeBasedEntityStore()
        {
            return GetString("StoreNotICodeBasedEntityStore");
        }

        /// <summary>
        /// Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIEagerLoadingEntityStore
        {
            get { return GetString("StoreNotIEagerLoadingEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIEagerLoadingEntityStore()
        {
            return GetString("StoreNotIEagerLoadingEntityStore");
        }

        /// <summary>
        /// Store does not implement IEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIEntityStore
        {
            get { return GetString("StoreNotIEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIEntityStore()
        {
            return GetString("StoreNotIEntityStore");
        }

        /// <summary>
        /// Store does not implement IEntityStore&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string StoreNotIEntityWithSubEntityStore
        {
            get { return GetString("StoreNotIEntityWithSubEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IEntityStore&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIEntityWithSubEntityStore()
        {
            return GetString("StoreNotIEntityWithSubEntityStore");
        }

        /// <summary>
        /// Store does not implement IFilterableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIFilterableEntityStore
        {
            get { return GetString("StoreNotIFilterableEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IFilterableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIFilterableEntityStore()
        {
            return GetString("StoreNotIFilterableEntityStore");
        }

        /// <summary>
        /// Store does not implement IGroupedEntityStore&lt;TEntity, TEntityGroup&gt;.
        /// </summary>
        internal static string StoreNotIGroupedEntityStore
        {
            get { return GetString("StoreNotIGroupedEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IGroupedEntityStore&lt;TEntity, TEntityGroup&gt;.
        /// </summary>
        internal static string FormatStoreNotIGroupedEntityStore()
        {
            return GetString("StoreNotIGroupedEntityStore");
        }

        /// <summary>
        /// Store does not implement IMasterDetailsEntityStore&lt;TEntity, TEntityDetail&gt;.
        /// </summary>
        internal static string StoreNotIMasterDetailsEntityStore
        {
            get { return GetString("StoreNotIMasterDetailsEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IMasterDetailsEntityStore&lt;TEntity, TEntityDetail&gt;.
        /// </summary>
        internal static string FormatStoreNotIMasterDetailsEntityStore()
        {
            return GetString("StoreNotIMasterDetailsEntityStore");
        }

        /// <summary>
        /// Store does not implement INameBasedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotINameBasedEntityStore
        {
            get { return GetString("StoreNotINameBasedEntityStore"); }
        }

        /// <summary>
        /// Store does not implement INameBasedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotINameBasedEntityStore()
        {
            return GetString("StoreNotINameBasedEntityStore");
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotIQueryableEntityStore
        {
            get { return GetString("StoreNotIQueryableEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIQueryableEntityStore()
        {
            return GetString("StoreNotIQueryableEntityStore");
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string StoreNotIQueryableEntityWithSubEntityStore
        {
            get { return GetString("StoreNotIQueryableEntityWithSubEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IQueryableEntityStore&lt;TEntity, TSubEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotIQueryableEntityWithSubEntityStore()
        {
            return GetString("StoreNotIQueryableEntityWithSubEntityStore");
        }

        /// <summary>
        /// Store does not implement IScopedNameBasedEntityStore&lt;TEntity, TEntityScope&gt;.
        /// </summary>
        internal static string StoreNotIScopedNameBasedEntityStore
        {
            get { return GetString("StoreNotIScopedNameBasedEntityStore"); }
        }

        /// <summary>
        /// Store does not implement IScopedNameBasedEntityStore&lt;TEntity, TEntityScope&gt;.
        /// </summary>
        internal static string FormatStoreNotIScopedNameBasedEntityStore()
        {
            return GetString("StoreNotIScopedNameBasedEntityStore");
        }

        /// <summary>
        /// Store does not implement ITimeTrackedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string StoreNotITimeTrackedEntityStore
        {
            get { return GetString("StoreNotITimeTrackedEntityStore"); }
        }

        /// <summary>
        /// Store does not implement ITimeTrackedEntityStore&lt;TEntity&gt;.
        /// </summary>
        internal static string FormatStoreNotITimeTrackedEntityStore()
        {
            return GetString("StoreNotITimeTrackedEntityStore");
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
