//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhantomNet.Entities {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhantomNet.Entities.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Optimistic concurrency failure, object has been modified..
        /// </summary>
        public static string ConcurrencyFailure {
            get {
                return ResourceManager.GetString("ConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An unknown failure has occured..
        /// </summary>
        public static string DefaultError {
            get {
                return ResourceManager.GetString("DefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Generic class {0} must also be used as class parameter..
        /// </summary>
        public static string GenericClassNotMatched {
            get {
                return ResourceManager.GetString("GenericClassNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement ICodeBasedEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotICodeBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotICodeBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IEagerLoadingEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotIEagerLoadingEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEagerLoadingEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotIEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IEntityStore&lt;TEntity, TSubEntity&gt;..
        /// </summary>
        public static string StoreNotIEntityWithSubEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIEntityWithSubEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IMasterDetailsEntityStore&lt;TEntity, TEntityDetail&gt;..
        /// </summary>
        public static string StoreNotIMasterDetailsEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIMasterDetailsEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement INameBasedEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotINameBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotINameBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IQueryableEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotIQueryableEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IQueryableEntityStore&lt;TEntity, TSubEntity&gt;..
        /// </summary>
        public static string StoreNotIQueryableEntityWithSubEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIQueryableEntityWithSubEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement IScopedNameBasedEntityStore&lt;TEntity, TEntityScope&gt;..
        /// </summary>
        public static string StoreNotIScopedNameBasedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotIScopedNameBasedEntityStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Store does not implement ITimeTrackedEntityStore&lt;TEntity&gt;..
        /// </summary>
        public static string StoreNotITimeTrackedEntityStore {
            get {
                return ResourceManager.GetString("StoreNotITimeTrackedEntityStore", resourceCulture);
            }
        }
    }
}
